img_size: [120,160]
top_cutoff: 40

detector:
  - line_detector.LineDetectorHSV
  - configuration:
      dilation_kernel_size: 3
      canny_thresholds: [ , ]	# Parametros filtro Canny
      hough_threshold: 20
      hough_min_line_length: 3
      hough_max_line_gap:    1

      # Regiones en HSV
      hsv_white1:  [ , , ]
      hsv_white2:  [ , , ]
      hsv_yellow1: [ , , ]
      hsv_yellow2: [ , , ]
      hsv_red1:    [ , , ]
      hsv_red2:    [ , , ]
      hsv_red3:    [ , , ]
      hsv_red4:    [ , , ]


detector_intersection:
 - line_detector.LineDetectorHSV
 - configuration:
     dilation_kernel_size: 3
     canny_thresholds: [1,2]
     hough_threshold: 2
     hough_min_line_length: 3
     hough_max_line_gap:    1

     hsv_white1:  [0,0,0]
     hsv_white2:  [255,255,255]
     hsv_yellow1: [0,0,0]
     hsv_yellow2: [255,255,255]
     hsv_red1:    [0,0,0]
     hsv_red2:    [255,255,255]
     hsv_red3:    [0,0,0]
     hsv_red4:    [255,255,255]
